-- Connect to sysdba user: SYS  via oracle client like sqldeveloper or
-- sqlplus:  connect / as sysdba

DEFINE owner_schema = SYS;
/

-- Create hospital database's tables

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE &owner_schema..DONVI CASCADE CONSTRAINT';
  EXCEPTION WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE  &owner_schema..DONVI(
ID_DONVI INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
TENDV NVARCHAR2(50),
CONSTRAINT DONVI_PK PRIMARY KEY(ID_DONVI)
);

/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE  &owner_schema..NHANVIEN CASCADE CONSTRAINT';
  EXCEPTION WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE  &owner_schema..NHANVIEN(
ID_NHANVIEN INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
TENNV NVARCHAR2(50) NOT NULL,
SDT VARCHAR2(50),
DIACHI NVARCHAR2(50),
GIOITINH NVARCHAR2(10),
NGAYSINH DATE,
LUONG NUMBER(9),
VAITRO NVARCHAR2(50),
DONVI INTEGER,
CONSTRAINT NHANVIEN_PK PRIMARY KEY (ID_NHANVIEN),
CONSTRAINT FK_DONVI_NHANVIEN FOREIGN KEY (DONVI) REFERENCES  &owner_schema..DONVI(ID_DONVI)
)
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE  &owner_schema..BENHNHAN CASCADE CONSTRAINT';
  EXCEPTION WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE  &owner_schema..BENHNHAN(
ID_BENHNHAN INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
HOTEN NVARCHAR2(50),
NGAYSINH DATE,
SDT VARCHAR2(50),
DIACHI NVARCHAR2(50),
GIOITINH NVARCHAR2(10),
NGHENGHIEP NVARCHAR2(50),
NOILAMVIEC NVARCHAR2(100),
SDTNGUOITHAN VARCHAR2(50),
CONSTRAINT BENHNHAN_PK PRIMARY KEY(ID_BENHNHAN)
);
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE  &owner_schema..HOSOBENHNHAN CASCADE CONSTRAINT';
  EXCEPTION WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE  &owner_schema..HOSOBENHNHAN(
ID_KHAMBENH INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
NGAYKB DATE,
ID_BENHNHAN INTEGER,
TINHTRANGBD NVARCHAR2(100),
KETLUANBS NVARCHAR2(100),
MATT INTEGER,
MABS INTEGER,
CONSTRAINT HOSOBENHNHAN_PK PRIMARY KEY(ID_KHAMBENH),
CONSTRAINT FK_BENHNHAN_HOSOBENHNHAN FOREIGN KEY(ID_BENHNHAN)REFERENCES  &owner_schema..BENHNHAN(ID_BENHNHAN),
CONSTRAINT FK_NV_BACSI_HOSOBENHNHAN FOREIGN KEY(MABS) REFERENCES  &owner_schema..NHANVIEN(ID_NHANVIEN),
CONSTRAINT FK_NV_TIEPTAN_HOSOBENHNHAN FOREIGN KEY(MATT) REFERENCES  &owner_schema..NHANVIEN(ID_NHANVIEN)
);
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE  &owner_schema..DICHVU CASCADE CONSTRAINT';
  EXCEPTION WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE  &owner_schema..DICHVU(
ID_DICHVU INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
TENDV NVARCHAR2(50),
DONGIA NUMBER(9),
CONSTRAINT DICHVU_PK PRIMARY KEY(ID_DICHVU)
);

/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE  &owner_schema..HOSO_DICHVU CASCADE CONSTRAINT';
  EXCEPTION WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE  &owner_schema..HOSO_DICHVU(
ID_KHAMBENH INTEGER,
ID_DICHVU INTEGER,
NGAYGIO TIMESTAMP,
NGUOITHUCHIEN INTEGER,
KETLUAN NVARCHAR2(100),
CONSTRAINT HS_DV_PK PRIMARY KEY(ID_KHAMBENH,ID_DICHVU),
CONSTRAINT FK_HOSOBENHNHAN_HS_DV FOREIGN KEY (ID_KHAMBENH) REFERENCES  &owner_schema..HOSOBENHNHAN(ID_KHAMBENH),
CONSTRAINT FK_DICHVU_HS_DV FOREIGN KEY (ID_DICHVU) REFERENCES  &owner_schema..DICHVU(ID_DICHVU),
CONSTRAINT FK_NHANVIEN_HS_DV FOREIGN KEY(NGUOITHUCHIEN) REFERENCES  &owner_schema..NHANVIEN(ID_NHANVIEN)
);
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE  &owner_schema..DONTHUOC CASCADE CONSTRAINT';
  EXCEPTION WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE  &owner_schema..DONTHUOC(
ID_DONTHUOC INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
ID_KHAMBENH INTEGER,
NVPT INTEGER,
CONSTRAINT DONTHUOC_PK PRIMARY KEY(ID_DONTHUOC),
CONSTRAINT FK_HOSOBENHNHAN_DONTHUOC FOREIGN KEY(ID_KHAMBENH) REFERENCES  &owner_schema..HOSOBENHNHAN(ID_KHAMBENH),
CONSTRAINT FK_NHANVIEN_DONTHUOC FOREIGN KEY (NVPT) REFERENCES  &owner_schema..NHANVIEN(ID_NHANVIEN)
);
/


BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE  &owner_schema..THUOC CASCADE CONSTRAINT';
  EXCEPTION WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE  &owner_schema..THUOC(
ID_THUOC INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
TENTHUOC NVARCHAR2(50),
DVT VARCHAR2(50),
DONGIA NUMBER(9,2),
LUUY NVARCHAR2(200),
XUATXU NVARCHAR2(50),
CONGDUNG NVARCHAR2(100),
CONSTRAINT THUOC_PK PRIMARY KEY(ID_THUOC)
);
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE  &owner_schema..CHITIETDONTHUOC CASCADE CONSTRAINT';
  EXCEPTION WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE  &owner_schema..CHITIETDONTHUOC(
ID_DONTHUOC INTEGER,
ID_THUOC INTEGER,
SOLUONG NUMBER (9),
LIEUDUNG NUMBER(9),
MOTA NVARCHAR2(100),
CONSTRAINT CT_DONTHUOC_PK PRIMARY KEY(ID_DONTHUOC,ID_THUOC),
CONSTRAINT FK_DONTHUOC_CTDONTHUOC FOREIGN KEY (ID_DONTHUOC) REFERENCES  &owner_schema..DONTHUOC(ID_DONTHUOC),
CONSTRAINT FK_THUOC_CTDONTHUOC FOREIGN KEY (ID_THUOC) REFERENCES  &owner_schema..THUOC(ID_THUOC)
);
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE  &owner_schema..HOADON CASCADE CONSTRAINT';
  EXCEPTION WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE  &owner_schema..HOADON(
ID_HOADON INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
ID_KHAMBENH INTEGER,
NGAYHD DATE,
NGUOIPT INTEGER,
PHUTHU NUMBER(9),
CONSTRAINT HOADON_PK PRIMARY KEY(ID_HOADON),
CONSTRAINT FK_HOSOBENHNHAN_HOADON FOREIGN KEY (ID_KHAMBENH) REFERENCES  &owner_schema..HOSOBENHNHAN(ID_KHAMBENH),
CONSTRAINT FK_NHANVIEN_HOADON FOREIGN KEY (NGUOIPT) REFERENCES  &owner_schema..NHANVIEN(ID_NHANVIEN)
);
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE  &owner_schema..CTHOADON CASCADE CONSTRAINT';
  EXCEPTION WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE  &owner_schema..CTHOADON(
ID_HOADON INTEGER,
ID_DICHVU INTEGER,
CONSTRAINT CTHOADON_PK PRIMARY KEY(ID_HOADON,ID_DICHVU),
CONSTRAINT FK_HOADON_CTHOADON FOREIGN KEY (ID_HOADON) REFERENCES  &owner_schema..HOADON(ID_HOADON),
CONSTRAINT FK_DICHVU_CTHOADON FOREIGN KEY (ID_DICHVU) REFERENCES  &owner_schema..DICHVU(ID_DICHVU)
);
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE  &owner_schema..CHAMCONG CASCADE CONSTRAINT';
  EXCEPTION WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE  &owner_schema..CHAMCONG(
ID_NHANVIEN INTEGER,
THOIGIAN TIMESTAMP,
CONSTRAINT FK_NHANVIEN_CHAMCONG FOREIGN KEY (ID_NHANVIEN) REFERENCES  &owner_schema..NHANVIEN(ID_NHANVIEN)
);
/
