-- Connect to user: benhvien (user created in 0.init.sql)
--  via an oracle client like sqldeveloper or
-- sqlplus: CONN BENHVIEN/ADMIN@//localhost:1521/pdb01.localdomain


---- Drop all tables ---

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE K_SALARY';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE K_SUBSALARY';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CHAMCONG';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CTHOADON';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE HOADON';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CHITIETDONTHUOC';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DONTHUOC';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE THUOC';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE HOSO_DICHVU';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE HOSOBENHNHAN';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DICHVU';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE BENHNHAN';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE NHANVIEN CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DONVI CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE LUONGTHANG';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CHINHANHBV CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE THONGBAO';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/


---- Create hospital database's tables ----

CREATE TABLE K_SALARY(
K_USER NVARCHAR2(50) NOT NULL,
K_KEY NVARCHAR2(50) NOT NULL
);
/
CREATE TABLE K_SUBSALARY(
K_USER NVARCHAR2(50) NOT NULL,
K_KEY NVARCHAR2(50) NOT NULL
);
/
CREATE TABLE CHINHANHBV(
ID_CHINHANH VARCHAR2(6) PRIMARY KEY,
TENCHINHANH NVARCHAR2(50) NOT NULL
);
/

CREATE TABLE DONVI(
ID_DONVI INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
TENDV NVARCHAR2(50),
VAITRO NVARCHAR2(50) NOT NULL,
CONSTRAINT DONVI_PK PRIMARY KEY(ID_DONVI),
CONSTRAINT DONVI_UQ UNIQUE (ID_DONVI, VAITRO)
);
/
CREATE TABLE NHANVIEN(
ID_NHANVIEN INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
TENNV NVARCHAR2(50) NOT NULL,
SDT VARCHAR2(50),
DIACHI NVARCHAR2(50),
GIOITINH NVARCHAR2(10),
NGAYSINH DATE,
LUONGCA NVARCHAR2(200),
PHUCAP  NVARCHAR2(200),
VAITRO NVARCHAR2(50) NOT NULL,
DONVI INTEGER,
CHINHANH VARCHAR2(6),
CONSTRAINT NHANVIEN_PK PRIMARY KEY (ID_NHANVIEN),
CONSTRAINT FK_CHINHANH_NHANVIEN FOREIGN KEY (CHINHANH) REFERENCES CHINHANHBV(ID_CHINHANH),
CONSTRAINT FK_DONVI_NHANVIEN FOREIGN KEY (DONVI) REFERENCES DONVI(ID_DONVI),
CONSTRAINT NHANVIEN_UQ UNIQUE (ID_NHANVIEN, VAITRO)
)
/
CREATE TABLE BENHNHAN(
ID_BENHNHAN INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
HOTEN NVARCHAR2(50),
NGAYSINH DATE,
SDT VARCHAR2(50),
DIACHI NVARCHAR2(50),
GIOITINH NVARCHAR2(10),
NGHENGHIEP NVARCHAR2(50),
NOILAMVIEC NVARCHAR2(100),
SDTNGUOITHAN VARCHAR2(50),
CONSTRAINT BENHNHAN_PK PRIMARY KEY(ID_BENHNHAN)
);
/
CREATE TABLE HOSOBENHNHAN(
ID_KHAMBENH INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
NGAYKB DATE,
ID_BENHNHAN INTEGER,
TINHTRANGBD NVARCHAR2(100),
KETLUANBS NVARCHAR2(100),
MATT INTEGER,
MABS INTEGER,
CONSTRAINT HOSOBENHNHAN_PK PRIMARY KEY(ID_KHAMBENH),
CONSTRAINT FK_BENHNHAN_HOSOBENHNHAN FOREIGN KEY(ID_BENHNHAN)REFERENCES BENHNHAN(ID_BENHNHAN),
CONSTRAINT FK_NV_BACSI_HOSOBENHNHAN FOREIGN KEY(MABS) REFERENCES NHANVIEN(ID_NHANVIEN),
CONSTRAINT FK_NV_TIEPTAN_HOSOBENHNHAN FOREIGN KEY(MATT) REFERENCES NHANVIEN(ID_NHANVIEN)
);
/
CREATE TABLE DICHVU(
ID_DICHVU INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
TENDV NVARCHAR2(50),
DONGIA NUMBER(9,2),
CONSTRAINT DICHVU_PK PRIMARY KEY(ID_DICHVU)
);
/
CREATE TABLE HOSO_DICHVU(
ID_KHAMBENH INTEGER,
ID_DICHVU INTEGER,
NGAYGIO TIMESTAMP,
NGUOITHUCHIEN INTEGER,
KETLUAN NVARCHAR2(100),
CONSTRAINT HS_DV_PK PRIMARY KEY(ID_KHAMBENH,ID_DICHVU),
CONSTRAINT FK_HOSOBENHNHAN_HS_DV FOREIGN KEY (ID_KHAMBENH) REFERENCES HOSOBENHNHAN(ID_KHAMBENH),
CONSTRAINT FK_DICHVU_HS_DV FOREIGN KEY (ID_DICHVU) REFERENCES DICHVU(ID_DICHVU),
CONSTRAINT FK_NHANVIEN_HS_DV FOREIGN KEY(NGUOITHUCHIEN) REFERENCES NHANVIEN(ID_NHANVIEN)
);
/
CREATE TABLE DONTHUOC(
ID_DONTHUOC INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
ID_KHAMBENH INTEGER,
NGUOILAP INTEGER,
CONSTRAINT DONTHUOC_PK PRIMARY KEY(ID_DONTHUOC),
CONSTRAINT FK_HOSOBENHNHAN_DONTHUOC FOREIGN KEY(ID_KHAMBENH) REFERENCES HOSOBENHNHAN(ID_KHAMBENH),
CONSTRAINT FK_NHANVIEN_DONTHUOC FOREIGN KEY (NGUOILAP) REFERENCES NHANVIEN(ID_NHANVIEN)
);
/
CREATE TABLE THUOC(
ID_THUOC INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
TENTHUOC NVARCHAR2(50),
DVT VARCHAR2(50),
DONGIA NUMBER(9,2),
LUUY NVARCHAR2(100),
XUATXU NVARCHAR2(50),
CONGDUNG NVARCHAR2(100),
CONSTRAINT THUOC_PK PRIMARY KEY(ID_THUOC)
);
/
CREATE TABLE CHITIETDONTHUOC(
ID_DONTHUOC INTEGER,
ID_THUOC INTEGER,
SOLUONG NUMBER (9),
LIEUDUNG VARCHAR(20),
MOTA NVARCHAR2(100),
CONSTRAINT CT_DONTHUOC_PK PRIMARY KEY(ID_DONTHUOC,ID_THUOC),
CONSTRAINT FK_DONTHUOC_CTDONTHUOC FOREIGN KEY (ID_DONTHUOC) REFERENCES DONTHUOC(ID_DONTHUOC),
CONSTRAINT FK_THUOC_CTDONTHUOC FOREIGN KEY (ID_THUOC) REFERENCES THUOC(ID_THUOC)
);
/
CREATE TABLE HOADON(
ID_HOADON INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
ID_KHAMBENH INTEGER,
NGAYHD DATE,
NGUOIPT INTEGER,
TONGTIEN NUMBER(9),
CONSTRAINT HOADON_PK PRIMARY KEY(ID_HOADON),
CONSTRAINT FK_HOSOBENHNHAN_HOADON FOREIGN KEY (ID_KHAMBENH) REFERENCES HOSOBENHNHAN(ID_KHAMBENH),
CONSTRAINT FK_NHANVIEN_HOADON FOREIGN KEY (NGUOIPT) REFERENCES NHANVIEN(ID_NHANVIEN)
);
/
CREATE TABLE CTHOADON(
ID_HOADON INTEGER,
ID_DICHVU INTEGER,
CONSTRAINT CTHOADON_PK PRIMARY KEY(ID_HOADON,ID_DICHVU),
CONSTRAINT FK_HOADON_CTHOADON FOREIGN KEY (ID_HOADON) REFERENCES HOADON(ID_HOADON),
CONSTRAINT FK_DICHVU_CTHOADON FOREIGN KEY (ID_DICHVU) REFERENCES DICHVU(ID_DICHVU)
);
/
CREATE TABLE CHAMCONG(
ID_NHANVIEN INTEGER,
THOIGIAN TIMESTAMP
);
/

CREATE TABLE LUONGTHANG(
THANG INTEGER NOT NULL,
NAM INTEGER NOT NULL,
ID_NHANVIEN INTEGER NOT NULL,
NGUOILAP INTEGER,
TONGTIEN INTEGER,
CONSTRAINT LUONGTHANG_PK PRIMARY KEY(THANG, NAM, ID_NHANVIEN),
CONSTRAINT FK_NHANVIEN_LUONGTHANG FOREIGN KEY (ID_NHANVIEN) REFERENCES NHANVIEN(ID_NHANVIEN),
CONSTRAINT FK_KETOAN_LUONGTHANG FOREIGN KEY (NGUOILAP) REFERENCES NHANVIEN(ID_NHANVIEN)
);
/

CREATE TABLE THONGBAO(
ID_VANBAN INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
ID_CHINHANH VARCHAR2(6),
ID_DONVI INTEGER,
NOIDUNG NVARCHAR2(2000) NOT NULL,
CONSTRAINT THONGBAO_PK PRIMARY KEY(ID_VANBAN),
CONSTRAINT FK_CHINHANHBV_THONGBAO FOREIGN KEY (ID_CHINHANH) REFERENCES CHINHANHBV(ID_CHINHANH),
CONSTRAINT FK_DONVI_THONGBAO FOREIGN KEY (ID_DONVI) REFERENCES DONVI(ID_DONVI)
);
/
---- Create synonym for tables ---

CREATE OR REPLACE PUBLIC SYNONYM DONVI FOR DONVI;
CREATE OR REPLACE PUBLIC SYNONYM CHINHANHBV FOR CHINHANHBV;
CREATE OR REPLACE PUBLIC SYNONYM NHANVIEN FOR NHANVIEN;
CREATE OR REPLACE PUBLIC SYNONYM BENHNHAN FOR BENHNHAN;
CREATE OR REPLACE PUBLIC SYNONYM HOSOBENHNHAN FOR HOSOBENHNHAN;
CREATE OR REPLACE PUBLIC SYNONYM DICHVU FOR DICHVU;
CREATE OR REPLACE PUBLIC SYNONYM HOSO_DICHVU FOR HOSO_DICHVU;
CREATE OR REPLACE PUBLIC SYNONYM DONTHUOC FOR DONTHUOC;
CREATE OR REPLACE PUBLIC SYNONYM THUOC FOR THUOC;
CREATE OR REPLACE PUBLIC SYNONYM CHITIETDONTHUOC FOR CHITIETDONTHUOC;
CREATE OR REPLACE PUBLIC SYNONYM HOADON FOR HOADON;
CREATE OR REPLACE PUBLIC SYNONYM CTHOADON FOR CTHOADON;
CREATE OR REPLACE PUBLIC SYNONYM CHAMCONG FOR CHAMCONG;
CREATE OR REPLACE PUBLIC SYNONYM LUONGTHANG FOR LUONGTHANG;
CREATE OR REPLACE PUBLIC SYNONYM K_SALARY FOR K_SALARY;
CREATE OR REPLACE PUBLIC SYNONYM K_SUBSALARY FOR K_SUBSALARY;
CREATE OR REPLACE PUBLIC SYNONYM THONGBAO FOR THONGBAO;

GRANT SELECT, INSERT ON CHAMCONG TO PUBLIC;