-- CONN BENHVIEN/ADMIN@//localhost:1521/pdb01.localdomain

-- Drop roles and users
BEGIN
  EXECUTE IMMEDIATE 'DROP ROLE NHANVIEN_QUANLY';
  EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP ROLE NHANVIEN_QUANLY_TAINGUYEN_NHANSU';
   EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP ROLE NHANVIEN_QUANLY_TAIVU';
   EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP ROLE NHANVIEN_QUANLY_CHUYENMON';
   EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP ROLE NHANVIEN_TIEPTAN_DIEUPHOI';
   EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP ROLE NHANVIEN_BANTHUOC';
   EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP ROLE NHANVIEN_TAIVU';
   EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP ROLE NHANVIEN_KETOAN';
   EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP ROLE BACSI_DIEUTRI';
   EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP USER NVQLTN01 CASCADE';
   EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP ROLE NVQLTV01 CASCADE';
   EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP ROLE NVQLCM01 CASCADE';
   EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP ROLE NVTT01 CASCADE';
   EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP ROLE NVBT01 CASCADE';
   EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP ROLE NVTV01 CASCADE';
   EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP ROLE NVKT01 CASCADE';
   EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP ROLE BS01 CASCADE';
   EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP ROLE BS02 CASCADE';
   EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Execute create roles
-- Input: (role name)
EXECUTE create_role('NHANVIEN_QUANLY');
EXECUTE create_role('NHANVIEN_QUANLY_TAINGUYEN_NHANSU');
EXECUTE create_role('NHANVIEN_QUANLY_TAIVU');
EXECUTE create_role('NHANVIEN_QUANLY_CHUYENMON');
EXECUTE create_role('NHANVIEN_TIEPTAN_DIEUPHOI');
EXECUTE create_role('NHANVIEN_BANTHUOC');
EXECUTE create_role('NHANVIEN_TAIVU');
EXECUTE create_role('NHANVIEN_KETOAN');
EXECUTE create_role('BACSI_DIEUTRI');


-- Execute create users
-- Input: (username, password)
EXECUTE create_user('NVQLTN01','NVQLTN01');
EXECUTE create_user('NVQLTV01','NVQLTV01');
EXECUTE create_user('NVQLCM01','NVQLCM01');
EXECUTE create_user('NVTT01','NVTT01');
EXECUTE create_user('NVBT01','NVBT01');
EXECUTE create_user('NVTV01','NVTV01');
EXECUTE create_user('NVKT01','NVKT01');
EXECUTE create_user('NVKT02','NVKT02');
EXECUTE create_user('BS01','BS01');
EXECUTE create_user('BS02','BS02');

EXECUTE create_user('NVQLTN02','NVQLTN02');
EXECUTE create_user('NVQLTV02','NVQLTV02');
EXECUTE create_user('NVQLCM02','NVQLCM02');
EXECUTE create_user('NVTT02','NVTT02');
EXECUTE create_user('NVBT02','NVBT02');
EXECUTE create_user('NVTV02','NVTV02');
EXECUTE create_user('NVKT03','NVKT03');
EXECUTE create_user('NVKT04','NVKT04');
EXECUTE create_user('BS03','BS03');
EXECUTE create_user('BS04','BS04');

EXECUTE create_user('NVQLTN03','NVQLTN03');
EXECUTE create_user('NVQLTV03','NVQLTV03');
EXECUTE create_user('NVQLCM03','NVQLCM03');
EXECUTE create_user('NVTT03','NVTT03');
EXECUTE create_user('NVBT03','NVBT03');
EXECUTE create_user('NVTV03','NVTV03');
EXECUTE create_user('NVKT05','NVKT05');
EXECUTE create_user('NVKT06','NVKT06');
EXECUTE create_user('BS05','BS05');
EXECUTE create_user('BS06','BS06');



-------RBAC policies----------


-- Execute grant privileges to roles
-- Input: (role name)
EXECUTE grant_quanLy_privs('NHANVIEN_QUANLY');
EXECUTE grant_quanlytainguyen_privs('NHANVIEN_QUANLY_TAINGUYEN_NHANSU');
EXECUTE grant_quanlytaivu_privs('NHANVIEN_QUANLY_TAIVU');
EXECUTE grant_tieptan_privs('NHANVIEN_TIEPTAN_DIEUPHOI');
EXECUTE grant_ban_thuoc_privs('NHANVIEN_BANTHUOC');
EXECUTE grant_taivu_privs('NHANVIEN_TAIVU');
EXECUTE grant_ketoan_privs('NHANVIEN_KETOAN');
EXECUTE grant_bacsi_privs('BACSI_DIEUTRI');

-- Execute grant role to roles
-- Input: (soure name, dest name)
EXECUTE grant_role_to_role_or_user('NHANVIEN_QUANLY', 'NHANVIEN_QUANLY_TAINGUYEN_NHANSU');
EXECUTE grant_role_to_role_or_user('NHANVIEN_QUANLY', 'NHANVIEN_QUANLY_TAIVU');
EXECUTE grant_role_to_role_or_user('NHANVIEN_QUANLY', 'NHANVIEN_QUANLY_CHUYENMON');
EXECUTE grant_role_to_role_or_user('NHANVIEN_TIEPTAN_DIEUPHOI', 'NVTT01');
EXECUTE grant_role_to_role_or_user('NHANVIEN_BANTHUOC', 'NVBT01');
EXECUTE grant_role_to_role_or_user('NHANVIEN_TAIVU', 'NVTV01');
EXECUTE grant_role_to_role_or_user('NHANVIEN_TIEPTAN_DIEUPHOI', 'NVTT02');
EXECUTE grant_role_to_role_or_user('NHANVIEN_BANTHUOC', 'NVBT02');
EXECUTE grant_role_to_role_or_user('NHANVIEN_TAIVU', 'NVTV02');
EXECUTE grant_role_to_role_or_user('NHANVIEN_TIEPTAN_DIEUPHOI', 'NVTT03');
EXECUTE grant_role_to_role_or_user('NHANVIEN_BANTHUOC', 'NVBT03');
EXECUTE grant_role_to_role_or_user('NHANVIEN_TAIVU', 'NVTV03');

-- Execute grant role to users
-- Input: (soure name, dest name)
EXECUTE grant_role_to_role_or_user('NHANVIEN_QUANLY_TAINGUYEN_NHANSU', 'NVQLTN01');
EXECUTE grant_role_to_role_or_user('NHANVIEN_QUANLY_TAIVU', 'NVQLTV01');
EXECUTE grant_role_to_role_or_user('NHANVIEN_QUANLY_CHUYENMON', 'NVQLCM01');
EXECUTE grant_role_to_role_or_user('NHANVIEN_KETOAN', 'NVKT01');
EXECUTE grant_role_to_role_or_user('NHANVIEN_KETOAN', 'NVKT02');
EXECUTE grant_role_to_role_or_user('BACSI_DIEUTRI', 'BS01');
EXECUTE grant_role_to_role_or_user('BACSI_DIEUTRI', 'BS02');
EXECUTE grant_role_to_role_or_user('NHANVIEN_QUANLY_TAINGUYEN_NHANSU', 'NVQLTN02');
EXECUTE grant_role_to_role_or_user('NHANVIEN_QUANLY_TAIVU', 'NVQLTV02');
EXECUTE grant_role_to_role_or_user('NHANVIEN_QUANLY_CHUYENMON', 'NVQLCM02');
EXECUTE grant_role_to_role_or_user('NHANVIEN_KETOAN', 'NVKT03');
EXECUTE grant_role_to_role_or_user('NHANVIEN_KETOAN', 'NVKT04');
EXECUTE grant_role_to_role_or_user('BACSI_DIEUTRI', 'BS03');
EXECUTE grant_role_to_role_or_user('BACSI_DIEUTRI', 'BS04');
EXECUTE grant_role_to_role_or_user('NHANVIEN_QUANLY_TAINGUYEN_NHANSU', 'NVQLTN03');
EXECUTE grant_role_to_role_or_user('NHANVIEN_QUANLY_TAIVU', 'NVQLTV03');
EXECUTE grant_role_to_role_or_user('NHANVIEN_QUANLY_CHUYENMON', 'NVQLCM03');
EXECUTE grant_role_to_role_or_user('NHANVIEN_KETOAN', 'NVKT05');
EXECUTE grant_role_to_role_or_user('NHANVIEN_KETOAN', 'NVKT06');
EXECUTE grant_role_to_role_or_user('BACSI_DIEUTRI', 'BS05');
EXECUTE grant_role_to_role_or_user('BACSI_DIEUTRI', 'BS06');



-------DAC policies----------


EXECUTE create_role('ALLOW_CONNECT');
EXECUTE create_role('ALLOW_UPDATE_SERVICE_PRICE');
EXECUTE grant_login_role_privs('ALLOW_CONNECT');
EXECUTE grant_update_service_price_role_privs('ALLOW_UPDATE_SERVICE_PRICE');


-- Input: (role name, username)
-- Policy 1: allow/deny login
EXECUTE grant_role_with_admin_option('ALLOW_CONNECT', 'NHANVIEN_QUANLY_TAINGUYEN_NHANSU');
EXECUTE grant_role_to_role_or_user('ALLOW_CONNECT', 'NHANVIEN_QUANLY_TAIVU');
EXECUTE grant_role_to_role_or_user('ALLOW_CONNECT', 'NHANVIEN_QUANLY_CHUYENMON');
-- EXECUTE grant_role_to_role_or_user('ALLOW_CONNECT', 'NVTT01');
-- EXECUTE grant_role_to_role_or_user('ALLOW_CONNECT', 'NVBT01');
-- EXECUTE grant_role_to_role_or_user('ALLOW_CONNECT', 'NVTV01');
-- EXECUTE grant_role_to_role_or_user('ALLOW_CONNECT', 'NVKT01');
-- EXECUTE grant_role_to_role_or_user('ALLOW_CONNECT', 'BS01');
-- EXECUTE grant_role_to_role_or_user('ALLOW_CONNECT', 'BS02');

-- Policy 2: allow TAIVU update DICHVU(DONGIA) 
EXECUTE grant_role_with_admin_option('ALLOW_UPDATE_SERVICE_PRICE', 'NHANVIEN_QUANLY_TAIVU');
-- EXECUTE grant_role_to_role_or_user('ALLOW_UPDATE_SERVICE_PRICE', 'NVTV01');

grant select on THONGBAO to PUBLIC;